### ISSUE TITLE
Chybějící (?) zdroje

### ISSUE THREAD

**Issue by Kout** [martinpesout/frontend-resources#1]
## Knihy

- [Javascript For Web Designers](https://abookapart.com/products/javascript-for-web-designers) (2016; A Book Apart; Mat Marquis) ‒ rozečteno, co mě přilákalo, je záměr autora představit JS pro nevývojáře, sám je kódér
- [Practical SVG](https://abookapart.com/products/practical-svg) (2016; A Book Apart; Chris Coyier) ‒ četl jsem, doporučuji, čtivé, neužvaněné, praktické informace a aktuální stav věci
- [Getting Ready for CSS Grid Layout](https://abookapart.com/products/get-ready-for-css-grid-layout) ‒ rozečteno
- [The New CSS Layout](https://abookapart.com/products/the-new-css-layout) (2017; A Book Apart; Rachel Andrew) ‒ nemám, ale asi koupím

## Grid Layout

- [Grid by Example](https://gridbyexample.com/) ‒ přehledný úvod do Gridu od Rachel Andrew 

## Podcasty

- [Brus kódu](http://bruskodu.cz/) ‒ natáčení přerušeno, přesto může být stále zajímavé

---

Co přidat školu hrou, tj. věci jako je Flexbox Frog? Zaujaly mne tyto:

- [Grid Garden](http://cssgridgarden.com/) ‒ jednoduchá procvičovačka na osvojení syntaxe
- [Flexbox Zombies](http://flexboxzombies.com/p/flexbox-zombies) ‒ autor zasílá i newsletter věnvaný novému CSS layoutu
- [Grid Criters](http://geddski.teachable.com/p/gridcritters) ‒ týž autor, ale na rozdíl od zombies, které už uvolnil zdarma, toto stojí 145 $, takže jsem nezkusil…

**Comment by martinpesout** [comment]
Díky za feedback. Příklady určitě projdu a něco do seznamu určitě přidám.

Sekce "Škola hrou" mě také napadla 😄  Dám ji také prostor v seznamu.

**Comment by Kout** [comment]
Ještě mi tam chybí [CSS Tricks](https://css-tricks.com/) a do newsletterů lze přidat [Dev Tips](https://umaar.com/dev-tips/) (lze sledovat i na webu jako blog, příp. Twitter, on to všecko cpe do animovanejch GIFů).

**Comment by martinpesout** [comment]
První věci jsem do seznamu doplnil. Zbytek zmíněných zdrojů bych chtěl ještě později projít. Musím prvně rozmyslet, jak to strukturovat. 

Zatím děkuji za pomoc.

**Comment by martinpesout** [comment]
Z knih jsem zatim pridal jen tu `Practical SVG`. Az budes mit docteny zbytek, tak napis, zda bude mit vyznam doplnit i ty ostatni do seznamu. 

Pro hry a prakticke ukazy jsem do seznamu pridal novou sekci. Zatim bych tam pridal jen ty uvedene, ktere je mozne vyzkouset bez registrace.

Diky moc za spolupraci. Pridal jsem te jako contributora do paticky seznamu 😄
