### ISSUE TITLE
Moje sbírka různých zdrojů

### ISSUE THREAD

**Issue by vojtaaa9** [martinpesout/frontend-resources#5]
Pár zdrojů :)

[Responsivní Design a jeho nejčastější chyby:](http://blog.kvasnickajan.cz/prakticky-pruvodce-nejcastejsimi-chybami-pri-navrhu-mobilniho-a-responzivniho-webu/)

[Rezponzivní framework pro emaily: ](https://mjml.io/)

a k tomu relevantní podpora různých klientů: 
[Campaign Monitor CSS:](https://www.campaignmonitor.com/css/) 

[Návod: Co má umět vývojář, aby mohl sebrat SEO specialistům práci: ](https://www.webexpo.cz/praha2017/prednaska/navod-co-ma-umet-vyvojar-aby-mohl-sebrat-seo-specialistum-praci/)

Možná to není vše relevatní, výběr nechám na tobě.

**Comment by martinpesout** [comment]
Díky. Projdu ty odkazy a zvážím to. Ozvu se.

**Comment by martinpesout** [comment]
Přidal jsem Campaign Monitor CSS do seznamu zdrojů: https://github.com/martinpesout/frontend-resources/pull/6

Určitě tam přidám i ty odkazy na zajímavé články, jen musím ještě rozmyslet, jak to pojmout. Snadno se totiž může stát, že seznam začne růst do neúměrné délky.

**Comment by vojtaaa9** [comment]
Jasný, však tam dej co považuješ za vhodné. Zavírám tím tento issue :)
